<script>
import HAssemblyRenderder from './HAssemblyRenderder.vue';

import {
    VAvatar,
    VAutocomplete,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VColorPicker,
    VCombobox,
    VContainer,
    VDatePicker,
    VDialog,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VCol,
    VFileInput,
    VIcon,
    VImg,
    VInput,
    VRow,
    VListItemContent,
    VListItemTitle,
    VMenu,
    VRadio,
    VRadioGroup,
    VRangeSlider,
    VSelect,
    VSlider,
    VSpacer,
    VSubheader,
    VSwitch,
    VTabs,
    VTab,
    VTabItem,
    VTextarea,
    VTextField,
    VTimePicker,
    VTooltip,
} from 'vuetify/lib';

export default {
    name: 'HFormRenderer',
    components: {
        VAvatar,
        VAutocomplete,
        VBtn,
        VCard,
        VCardActions,
        VCardText,
        VCardTitle,
        VCheckbox,
        VChip,
        VColorPicker,
        VCombobox,
        VContainer,
        VDatePicker,
        VDialog,
        VExpansionPanels,
        VExpansionPanel,
        VExpansionPanelHeader,
        VExpansionPanelContent,
        VCol,
        VFileInput,
        VIcon,
        VImg,
        VInput,
        VRow,
        VListItemContent,
        VListItemTitle,
        VMenu,
        VRadio,
        VRadioGroup,
        VRangeSlider,
        VSelect,
        VSlider,
        VSpacer,
        VSubheader,
        VSwitch,
        VTabs,
        VTab,
        VTabItem,
        VTextarea,
        VTextField,
        VTimePicker,
        VTooltip,
    },
    mixins: [HAssemblyRenderder],
};
</script>
